timeout: 300s
substitutions:
  _ACTION: apply
  _NAME: broker
  _REGION:
  _CUSTOM_DOMAIN: ""
  _LB_DOMAINS: ""
tags:
  - custom-domain
steps:
  ###
  # Cleanup any existing sub-jobs to prevent overlapping executions.
  ###
  - name: "gcr.io/cloud-builders/gcloud"
    id: cleanup-sub-jobs
    entrypoint: bash
    args:
      - -c
      - |
        gcloud -q builds list --ongoing --filter='tags[]~custom-domain-infra' --format='value(id)' | \
          xargs --no-run-if-empty gcloud -q builds cancel >/dev/null

  ###
  # Provision infrastructure to create secrets
  ###
  - name: "gcr.io/cloud-builders/gcloud"
    id: custom-domain-infra
    dir: infra
    entrypoint: "bash"
    args:
      - "-exc"
      - |
        gcloud builds submit --substitutions=^--^_NAME=${_NAME}--_ACTION=${_ACTION}--_REGION=${_REGION}--_CUSTOM_DOMAIN=${_CUSTOM_DOMAIN}--_LB_DOMAINS=${_LB_DOMAINS}